

server:
  port: 10001



spring:
  datasource:
    dynamic:
      primary: user-ds #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        user-ds:
          url: jdbc:mysql://localhost:3306/user_ds?autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
        article-ds:
          url: jdbc:mysql://localhost:3306/article_ds?autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          type: com.zaxxer.hikari.HikariDataSource
#        slave_2:
#          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
#          username: ENC(xxxxx)
#          password: ENC(xxxxx)
#          driver-class-name: com.mysql.jdbc.Driver
        #......省略
        #以上会配置一个默认库master，一个组slave下有两个子库slave_1,slave_2

#spring:
#  datasource:
#    user-ds:
#      url: jdbc:mysql://172.16.5.149:6006/pub?autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      type: com.zaxxer.hikari.HikariDataSource
#    article-ds:
#      url: jdbc:mysql://172.16.5.149:6006/pub?autoReconnect=true&useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#      username: root
#      password: 123456
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      type: com.zaxxer.hikari.HikariDataSource


